import { LogViewer } from "@/components/log-viewer"

export default function Page() {
  const sampleLogs = [
    {
      id: "1",
      timestamp: "2025-01-15 14:32:18.234",
      method: "POST" as const,
      endpoint: "/api/users/create",
      status: 201,
      duration: 145,
      request: {
        body: {
          name: "John Doe",
          email: "john@example.com",
          role: "admin",
        },
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer token123",
        },
      },
      response: {
        success: true,
        data: {
          id: "usr_123",
          name: "John Doe",
          email: "john@example.com",
          createdAt: "2025-01-15T14:32:18.234Z",
        },
      },
      children: [
        {
          id: "1-1",
          timestamp: "2025-01-15 14:32:18.250",
          method: "POST" as const,
          endpoint: "/db/users/insert",
          status: 200,
          duration: 45,
          request: { query: "INSERT INTO users..." },
          response: { rowsAffected: 1 },
        },
        {
          id: "1-2",
          timestamp: "2025-01-15 14:32:18.300",
          method: "POST" as const,
          endpoint: "/api/notifications/send",
          status: 200,
          duration: 67,
          request: { type: "welcome_email", userId: "usr_123" },
          response: { sent: true },
        },
        {
          id: "1-3",
          timestamp: "2025-01-15 14:32:18.350",
          method: "POST" as const,
          endpoint: "/api/analytics/track",
          status: 200,
          duration: 23,
          request: { event: "user_created", userId: "usr_123" },
          response: { tracked: true },
        },
      ],
    },
    {
      id: "2",
      timestamp: "2025-01-15 14:31:45.123",
      method: "GET" as const,
      endpoint: "/api/products?category=electronics&limit=20",
      status: 200,
      duration: 89,
      request: {
        query: {
          category: "electronics",
          limit: 20,
        },
      },
      response: {
        data: [
          { id: "prod_1", name: "Laptop", price: 999 },
          { id: "prod_2", name: "Mouse", price: 29 },
        ],
        total: 2,
      },
      children: [
        {
          id: "2-1",
          timestamp: "2025-01-15 14:31:45.140",
          method: "GET" as const,
          endpoint: "/db/products/query",
          status: 200,
          duration: 56,
          request: { filter: { category: "electronics" } },
          response: { count: 2 },
        },
        {
          id: "2-2",
          timestamp: "2025-01-15 14:31:45.180",
          method: "GET" as const,
          endpoint: "/cache/products/check",
          status: 200,
          duration: 12,
          request: { key: "products:electronics" },
          response: { hit: false },
        },
        {
          id: "2-3",
          timestamp: "2025-01-15 14:31:45.200",
          method: "POST" as const,
          endpoint: "/cache/products/set",
          status: 200,
          duration: 8,
          request: { key: "products:electronics", ttl: 300 },
          response: { cached: true },
        },
      ],
    },
    {
      id: "3",
      timestamp: "2025-01-15 14:30:12.567",
      method: "DELETE" as const,
      endpoint: "/api/sessions/usr_9876543210",
      status: 204,
      duration: 34,
      request: {
        params: {
          userId: "usr_9876543210",
        },
      },
      response: {},
      children: [
        {
          id: "3-1",
          timestamp: "2025-01-15 14:30:12.580",
          method: "DELETE" as const,
          endpoint: "/db/sessions/delete",
          status: 200,
          duration: 18,
          request: { userId: "usr_9876543210" },
          response: { deleted: 1 },
        },
        {
          id: "3-2",
          timestamp: "2025-01-15 14:30:12.595",
          method: "POST" as const,
          endpoint: "/api/audit/log",
          status: 200,
          duration: 12,
          request: { action: "session_deleted", userId: "usr_9876543210" },
          response: { logged: true },
        },
      ],
    },
    {
      id: "4",
      timestamp: "2025-01-15 14:29:33.891",
      method: "PUT" as const,
      endpoint: "/api/orders/ord_555/status",
      status: 200,
      duration: 112,
      request: {
        body: {
          status: "shipped",
          trackingNumber: "TRK123456",
        },
      },
      response: {
        success: true,
        order: {
          id: "ord_555",
          status: "shipped",
          updatedAt: "2025-01-15T14:29:33.891Z",
        },
      },
      children: [
        {
          id: "4-1",
          timestamp: "2025-01-15 14:29:33.910",
          method: "PUT" as const,
          endpoint: "/db/orders/update",
          status: 200,
          duration: 42,
          request: { orderId: "ord_555", status: "shipped" },
          response: { updated: true },
        },
        {
          id: "4-2",
          timestamp: "2025-01-15 14:29:33.950",
          method: "POST" as const,
          endpoint: "/api/notifications/email",
          status: 200,
          duration: 45,
          request: { template: "order_shipped", orderId: "ord_555" },
          response: { sent: true },
        },
        {
          id: "4-3",
          timestamp: "2025-01-15 14:29:33.980",
          method: "POST" as const,
          endpoint: "/api/webhooks/trigger",
          status: 200,
          duration: 18,
          request: { event: "order.shipped", orderId: "ord_555" },
          response: { triggered: true },
        },
      ],
    },
    {
      id: "5",
      timestamp: "2025-01-15 14:28:05.234",
      method: "POST" as const,
      endpoint: "/api/auth/login",
      status: 401,
      duration: 67,
      request: {
        body: {
          email: "user@example.com",
          password: "********",
        },
      },
      response: {
        error: "Invalid credentials",
        code: "AUTH_FAILED",
      },
      children: [
        {
          id: "5-1",
          timestamp: "2025-01-15 14:28:05.250",
          method: "GET" as const,
          endpoint: "/db/users/findByEmail",
          status: 200,
          duration: 28,
          request: { email: "user@example.com" },
          response: { found: true },
        },
        {
          id: "5-2",
          timestamp: "2025-01-15 14:28:05.280",
          method: "POST" as const,
          endpoint: "/auth/verify-password",
          status: 401,
          duration: 15,
          request: { hash: "bcrypt_hash" },
          response: { valid: false },
        },
        {
          id: "5-3",
          timestamp: "2025-01-15 14:28:05.295",
          method: "POST" as const,
          endpoint: "/api/audit/failed-login",
          status: 200,
          duration: 8,
          request: { email: "user@example.com", ip: "192.168.1.1" },
          response: { logged: true },
        },
      ],
    },
    {
      id: "6",
      timestamp: "2025-01-15 14:27:22.456",
      method: "GET" as const,
      endpoint: "/api/analytics/dashboard",
      status: 500,
      duration: 2345,
      request: {
        query: {
          dateRange: "last_30_days",
          metrics: ["revenue", "users", "orders"],
        },
      },
      response: {
        error: "Database connection timeout",
        code: "DB_TIMEOUT",
      },
      children: [
        {
          id: "6-1",
          timestamp: "2025-01-15 14:27:22.480",
          method: "GET" as const,
          endpoint: "/db/analytics/revenue",
          status: 500,
          duration: 2000,
          request: { dateRange: "last_30_days" },
          response: { error: "Connection timeout" },
        },
        {
          id: "6-2",
          timestamp: "2025-01-15 14:27:24.490",
          method: "POST" as const,
          endpoint: "/api/monitoring/alert",
          status: 200,
          duration: 45,
          request: { severity: "critical", message: "DB timeout" },
          response: { alerted: true },
        },
        {
          id: "6-3",
          timestamp: "2025-01-15 14:27:24.540",
          method: "POST" as const,
          endpoint: "/api/logs/error",
          status: 200,
          duration: 12,
          request: { error: "DB_TIMEOUT", endpoint: "/api/analytics/dashboard" },
          response: { logged: true },
        },
      ],
    },
    {
      id: "7",
      timestamp: "2025-01-15 14:26:18.789",
      method: "PATCH" as const,
      endpoint: "/api/users/usr_789/profile",
      status: 200,
      duration: 78,
      request: {
        body: {
          bio: "Updated bio text",
          avatar: "https://example.com/avatar.jpg",
        },
      },
      response: {
        success: true,
        user: {
          id: "usr_789",
          bio: "Updated bio text",
          avatar: "https://example.com/avatar.jpg",
        },
      },
      children: [
        {
          id: "7-1",
          timestamp: "2025-01-15 14:26:18.805",
          method: "PATCH" as const,
          endpoint: "/db/users/update",
          status: 200,
          duration: 38,
          request: { userId: "usr_789", fields: ["bio", "avatar"] },
          response: { updated: true },
        },
        {
          id: "7-2",
          timestamp: "2025-01-15 14:26:18.845",
          method: "DELETE" as const,
          endpoint: "/cache/users/invalidate",
          status: 200,
          duration: 8,
          request: { userId: "usr_789" },
          response: { invalidated: true },
        },
        {
          id: "7-3",
          timestamp: "2025-01-15 14:26:18.860",
          method: "POST" as const,
          endpoint: "/api/search/reindex",
          status: 200,
          duration: 22,
          request: { type: "user", id: "usr_789" },
          response: { reindexed: true },
        },
      ],
    },
  ]

  return <LogViewer logs={sampleLogs} />
}
